### ISSUE TITLE
Source code not available

### ISSUE THREAD

**Issue by DrraBL** [cherise215/CardiacMRSegmentation#1]
Hi 
first of all, I would like to express my deep interest in your great work. just if that works for you can share the code ?

I appreciate your help many thanks.
kind regards,

**Comment by cherise215** [comment]
Hi Please find the code at https://gitlab.doc.ic.ac.uk/cc215/Cardiac_Multi_view_segmentation

**Comment by DrraBL** [comment]
Many thanks 
I appreciate your help @cherise215
